### ISSUE TITLE
Any Source?

### ISSUE THREAD

**Issue by Wolf3s** [CristianoSword/Star-Car-SMS#1]

**Comment by CristianoSword** [comment]
Hi, sorry for the delay in replying, I actually didn't see the issue.
I believe that this week I will finish the code and compile, as soon as I do that, I will also upload a readme showing how to compile.

**Comment by Wolf3s** [comment]
> Hi, sorry for the delay in replying, I actually didn't see the issue. I believe that this week I will finish the code and compile, as soon as I do that, I will also upload a readme showing how to compile.

Oh fine but i see some new asm files here but i would see the game too but i will give you patience for that.

**Comment by CristianoSword** [comment]
> > Hi, sorry for the delay in replying, I actually didn't see the issue. I believe that this week I will finish the code and compile, as soon as I do that, I will also upload a readme showing how to compile.
> 
> Oh fine but i see some new asm files here but i would see the game too but i will give you patience for that.

I ended up leaving this little project aside, because of other projects of mine for the Mega Drive.
But basically I was following this tutorial from the SMS Power website, I'll leave the link below:
https://www.smspower.org/Articles/CreateARacingGame
